import { AppBar, Typography } from "@mui/material";
import Head from "next/head";
// Import components
import VideoPlayer from "@/components/VideoPlayer";
import Option from "@/components/Option";
import Notification from "@/components/Notification";

const Home = () => {
  return (
    <>
      <Head>
        <title>Video calling app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppBar position="static" color="inherit">
          <Typography variant="h2" align="center">
            Video chat
          </Typography>
        </AppBar>
        <VideoPlayer />
        <Option>
          <Notification />
        </Option>
      </main>
    </>
  );
};
export default Home;
